#!/usr/bin/env python3
"""Optional publication renderer. Requires reportlab and python-pptx.

SVGs generated by diagrams.py are converted to native PowerPoint shapes.
The slide PDF is a layout proxy, not a PowerPoint-engine rendering.
"""
from __future__ import annotations
import argparse
import html
import json
import math
import re
import textwrap
import xml.etree.ElementTree as ET
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import letter
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Flowable, KeepTogether
from pptx import Presentation
from pptx.util import Pt
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE, MSO_CONNECTOR
from pptx.oxml.xmlchemy import OxmlElement
from gates import ArtifactStore, file_hash

FONT = "Helvetica"
BOLD = "Helvetica-Bold"
for regular, bold in [
    (Path('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'), Path('/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'))
]:
    if regular.exists() and bold.exists():
        pdfmetrics.registerFont(TTFont("LoopSans", str(regular)))
        pdfmetrics.registerFont(TTFont("LoopSansBold", str(bold)))
        FONT, BOLD = "LoopSans", "LoopSansBold"
NAVY, TEAL, MUTED, LIGHT = "#15354C", "#087F82", "#52677A", "#F3F7F8"


def clean(text):
    return re.sub(r"[*`]", "", str(text))


def wrapped(text, width, size, bold=False):
    result = []
    for para in str(text).split("\n"):
        line = ""
        for word in para.split():
            candidate = (line + " " + word).strip()
            if line and pdfmetrics.stringWidth(candidate, BOLD if bold else FONT, size) > width:
                result.append(line); line = word
            else:
                line = candidate
        result.append(line)
    return result


class PdfSurface:
    def __init__(self, c, height):
        self.c, self.height = c, height

    def rect(self, x, y, w, h, fill, stroke=None, rounded=False):
        c = self.c
        c.setFillColor(colors.HexColor(fill))
        c.setStrokeColor(colors.HexColor(stroke or fill))
        c.setLineWidth(0.7)
        if rounded:
            c.roundRect(x, self.height-y-h, w, h, 6, fill=1, stroke=bool(stroke))
        else:
            c.rect(x, self.height-y-h, w, h, fill=1, stroke=bool(stroke))

    def text(self, text, x, y, w, size=20, color=NAVY, bold=False, anchor="start", line_height=None):
        c = self.c; c.setFillColor(colors.HexColor(color)); c.setFont(BOLD if bold else FONT, size)
        lh = line_height or size*1.28
        for i, line in enumerate(wrapped(text, w, size, bold)):
            px = x
            if anchor != "start":
                tw = pdfmetrics.stringWidth(line, BOLD if bold else FONT, size)
                px -= tw/2 if anchor == "middle" else tw
            c.drawString(px, self.height-y-size-i*lh, line)

    def line(self, points, color=MUTED, width=1.5, arrow=False):
        c = self.c; c.setStrokeColor(colors.HexColor(color)); c.setLineWidth(width)
        path = c.beginPath(); path.moveTo(points[0][0], self.height-points[0][1])
        for x, y in points[1:]: path.lineTo(x, self.height-y)
        c.drawPath(path)
        if arrow and len(points)>1:
            (px,py),(x,y)=points[-2:]; ang=math.atan2(y-py,x-px); length=max(5,width*4)
            p=c.beginPath();p.moveTo(x,self.height-y)
            for off in (-0.5,0.5):
                p.lineTo(x-length*math.cos(ang+off),self.height-(y-length*math.sin(ang+off)))
            p.close();c.setFillColor(colors.HexColor(color));c.drawPath(p,fill=1,stroke=0)


class PptSurface:
    def __init__(self, slide):
        self.slide=slide

    def rect(self, x, y, w, h, fill, stroke=None, rounded=False):
        s=self.slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE if rounded else MSO_SHAPE.RECTANGLE, Pt(x),Pt(y),Pt(w),Pt(h))
        if rounded:
            s.adjustments[0] = 0.06
        s.fill.solid();s.fill.fore_color.rgb=RGBColor.from_string(fill.lstrip('#'))
        if stroke:
            s.line.color.rgb=RGBColor.from_string(stroke.lstrip('#'));s.line.width=Pt(.7)
        else: s.line.fill.background()

    def text(self, text, x, y, w, size=20, color=NAVY, bold=False, anchor="start", line_height=None):
        lines=wrapped(text,w,size,bold)
        lh=line_height or size*1.28
        for i,line in enumerate(lines):
            tw=pdfmetrics.stringWidth(line,BOLD if bold else FONT,size)
            px=x-(tw/2 if anchor=='middle' else tw if anchor=='end' else 0)
            box=self.slide.shapes.add_textbox(Pt(px),Pt(y+i*lh-1),Pt(tw+8),Pt(lh+6))
            tf=box.text_frame;tf.clear();tf.margin_left=tf.margin_right=tf.margin_top=tf.margin_bottom=0
            tf.word_wrap=False
            p=tf.paragraphs[0];p.text=line;p.font.name="DejaVu Sans";p.font.size=Pt(size);p.font.bold=bold
            p.font.color.rgb=RGBColor.from_string(color.lstrip('#'))

    def line(self, points, color=MUTED, width=1.5, arrow=False):
        for i,((x,y),(tx,ty)) in enumerate(zip(points,points[1:])):
            line=self.slide.shapes.add_connector(MSO_CONNECTOR.STRAIGHT,Pt(x),Pt(y),Pt(tx),Pt(ty))
            line.line.color.rgb=RGBColor.from_string(color.lstrip('#'));line.line.width=Pt(width)
            if arrow and i==len(points)-2:
                tail=OxmlElement('a:tailEnd');tail.set('type','triangle');line._element.spPr.get_or_add_ln().append(tail)


def svg(surface, path, x, y, w, h):
    """Render the deliberately restricted SVG dialect produced by diagrams.py."""
    root=ET.parse(path).getroot()
    sw,sh=float(root.attrib['width']),float(root.attrib['height'])
    scale=min(w/sw,h/sh); ox=x+(w-sw*scale)/2; oy=y+(h-sh*scale)/2
    for e in root:
        tag=e.tag.rsplit('}',1)[-1]; a=e.attrib
        if tag=='rect':
            surface.rect(ox+float(a.get('x',0))*scale,oy+float(a.get('y',0))*scale,
                         float(a['width'])*scale,float(a['height'])*scale,a.get('fill','#FFFFFF'),a.get('stroke'),bool(a.get('rx')))
        elif tag=='text':
            size=float(a.get('font-size',16))*scale
            # SVG positions text at the baseline; the surfaces use top coordinates.
            surface.text(''.join(e.itertext()),ox+float(a['x'])*scale,oy+float(a['y'])*scale-size,
                         max(sw*scale,1),size,a.get('fill',NAVY),a.get('font-weight')=='bold',a.get('text-anchor','start'),size*1.2)
        elif tag=='polyline':
            pts=[[ox+float(v.split(',')[0])*scale,oy+float(v.split(',')[1])*scale] for v in a['points'].split()]
            surface.line(pts,a.get('stroke',MUTED),float(a.get('stroke-width',2))*scale,bool(a.get('marker-end')))


class SvgFigure(Flowable):
    def __init__(self,path,width):
        super().__init__(); self.path=path
        root=ET.parse(path).getroot(); ratio=float(root.attrib['height'])/float(root.attrib['width'])
        self.width=width;self.height=min(490,width*ratio)
    def draw(self):
        svg(PdfSurface(self.canv,self.height),self.path,0,0,self.width,self.height)


def markup(text):
    s=html.escape(text)
    s=re.sub(r'\*\*(.+?)\*\*',r'<b>\1</b>',s)
    s=re.sub(r'`([^`]+)`',r'<font name="Courier">\1</font>',s)
    s=re.sub(r'\[([^\]]+)\]\((https?://[^)]+)\)',r'<link href="\2" color="#087F82">\1</link>',s)
    return s


def paper_pdf(root,out):
    styles=getSampleStyleSheet()
    styles.add(ParagraphStyle(name='PaperBody',fontName=FONT,fontSize=10,leading=15,textColor=colors.HexColor(NAVY),spaceAfter=9))
    styles.add(ParagraphStyle(name='PaperTitle',fontName=BOLD,fontSize=27,leading=33,spaceAfter=19,textColor=colors.HexColor(NAVY)))
    styles.add(ParagraphStyle(name='PaperH2',fontName=BOLD,fontSize=16,leading=22,spaceBefore=15,spaceAfter=10,keepWithNext=True,textColor=colors.HexColor(TEAL)))
    styles.add(ParagraphStyle(name='PaperH3',fontName=BOLD,fontSize=12,leading=17,spaceBefore=12,spaceAfter=7,keepWithNext=True,textColor=colors.HexColor(NAVY)))
    styles.add(ParagraphStyle(name='Caption',fontName=FONT,fontSize=8.5,leading=12,textColor=colors.HexColor(MUTED),spaceAfter=12))
    views={v['id']:v for v in json.loads((root/'architecture.json').read_text())['views']}
    story=[];paragraph=[];incode=False
    def flush():
        if paragraph:
            story.append(Paragraph(markup(' '.join(paragraph)),styles['PaperBody']));paragraph.clear()
    for line in (root/'paper.md').read_text().splitlines():
        if line.startswith('```'):
            flush();incode=not incode;continue
        if line.strip()=='<!-- pagebreak -->':
            flush();story.append(PageBreak());continue
        if line.startswith('<!--'):continue
        if not line.strip():flush();continue
        m=re.fullmatch(r'\[Figure:([^\]]+)\]',line.strip())
        if m:
            flush();v=views[m[1]]
            story.append(KeepTogether([SvgFigure(root/'diagrams'/f'{m[1]}.svg',480),Paragraph(markup(v['caption']),styles['Caption'])]));continue
        if line.startswith('# '):flush();story.append(Paragraph(markup(line[2:]),styles['PaperTitle']));continue
        if line.startswith('## '):flush();story.append(Paragraph(markup(line[3:]),styles['PaperH2']));continue
        if line.startswith('### '):flush();story.append(Paragraph(markup(line[4:]),styles['PaperH3']));continue
        if line.startswith('- '):flush();story.append(Paragraph('• '+markup(line[2:]),styles['PaperBody']));continue
        if incode:flush();story.append(Paragraph(markup(line),styles['Caption']));continue
        paragraph.append(line)
    flush()
    def footer(c,doc):
        c.setStrokeColor(colors.HexColor('#D6E1E5'));c.line(54,44,558,44)
        c.setFont(FONT,8);c.setFillColor(colors.HexColor(MUTED))
        c.drawString(54,29,'ARCHITECTURE LOOP  /  ARCHITECTURE PAPER');c.drawRightString(558,29,str(doc.page))
    SimpleDocTemplate(str(out),pagesize=letter,rightMargin=66,leftMargin=66,topMargin=48,bottomMargin=62,
                      title=json.loads((root/'slides.json').read_text()).get('title','Architecture paper'),author='Architecture Loop').build(story,onFirstPage=footer,onLaterPages=footer)


def slide_layout(surface,slide,n,total,root):
    surface.rect(0,0,960,540,'#FFFFFF')
    surface.rect(0,0,960,7,TEAL)
    surface.text(slide.get('kicker','ARCHITECTURE LOOP'),36,24,880,11,TEAL,True)
    title_lines=wrapped(slide['title'],886,29,True)
    if len(title_lines)>2: raise ValueError(f"Slide {slide['id']} title is too long")
    surface.text(slide['title'],36,45,886,29,NAVY,True)
    top=115 if len(title_lines)==1 else 139
    views=slide.get('view_ids',[])
    if views:
        if len(views)>1:raise ValueError('Use one C4 view per slide')
        svg(surface,root/'diagrams'/f'{views[0]}.svg',24,top-20,912,380-(top-115))
        surface.text(slide['takeaway'],36,472,890,15,NAVY,True)
    else:
        surface.text(slide['takeaway'],36,top,875,20,MUTED,False)
        cards=slide.get('cards',[])
        if cards:
            count=len(cards)
            if count>3:raise ValueError('At most three cards per slide')
            cw=(888-(count-1)*18)/count
            cardtop=top+80
            for i,card in enumerate(cards):
                x=36+i*(cw+18)
                surface.rect(x,cardtop,cw,224,LIGHT,rounded=True)
                surface.rect(x,cardtop,5,224,TEAL)
                surface.text(card['heading'],x+20,cardtop+18,cw-39,20,NAVY,True)
                bodyy=cardtop+75
                body=card['body']
                lines=wrapped(body,cw-40,17)
                if len(lines)>6:raise ValueError(f"Slide {slide['id']} card text exceeds 6 lines")
                surface.text(body,x+20,bodyy,cw-40,17,MUTED)
        else:
            yy=top+82
            for b in slide.get('bullets',[]):
                surface.rect(40,yy+9,6,6,TEAL)
                lines=wrapped(b,842,21)
                surface.text(b,61,yy,842,21,NAVY)
                yy+=max(56,len(lines)*27+20)
            if yy>485:raise ValueError(f"Slide {slide['id']} body overflows")
    surface.line([[36,510],[924,510]],'#D6E1E5',.7)
    refs=', '.join(slide.get('claim_ids',[]))
    surface.text(f"{slide['id']}  •  {slide['paper_section']}  •  Claims: {refs}",36,519,800,8,MUTED)
    surface.text(f'{n:02d} / {total:02d}',924,519,60,8,MUTED,anchor='end')


def render(root):
    store=ArtifactStore(root);data=store.read('slides.json');ev=store.read('evidence.json')
    out=store.path('output');out.mkdir(exist_ok=True)
    stem=store.read('brief.json').get('output_stem','Architecture')
    if not re.fullmatch(r'[A-Za-z0-9_-]+',stem): raise ValueError('Unsafe output stem')
    paper=out/f'{stem}_Paper.pdf'
    deck=out/f'{stem}_Slides.pptx'
    proxy=out/f'{stem}_Slides_Preview.pdf'
    # Filenames are customizable by renaming and updating export.json.
    paper_pdf(store.root,paper)
    prs=Presentation();prs.slide_width=Pt(960);prs.slide_height=Pt(540)
    prs.core_properties.title=data['title'];prs.core_properties.subject=data.get('subtitle','')
    prs.core_properties.author='Architecture Loop'
    c=canvas.Canvas(str(proxy),pagesize=(960,540));c.setTitle(data['title']+' — layout preview')
    claims={x['id']:x for x in ev['claims']};sources={x['id']:x for x in ev['sources']}
    for i,row in enumerate(data['slides']):
        slide=prs.slides.add_slide(prs.slide_layouts[6])
        slide_layout(PptSurface(slide),row,i+1,len(data['slides']),store.root)
        slide_layout(PdfSurface(c,540),row,i+1,len(data['slides']),store.root);c.showPage()
        source_ids=sorted({s for cid in row.get('claim_ids',[]) for s in claims[cid].get('source_ids',[])})
        refs='\n'.join(f"{s}: {sources[s]['title']} — {sources[s]['url']}" for s in source_ids)
        slide.notes_slide.notes_text_frame.text=row['speaker_notes']+'\n\nPaper section: '+row['paper_section']+'\nSources:\n'+refs
    c.save();prs.save(deck)
    files=[]
    for p,fmt in [(paper,'pdf'),(deck,'pptx'),(proxy,'pdf')]:
        files.append({'path':str(p.relative_to(store.root)),'format':fmt,'sha256':file_hash(p),'inspected':False,'inspection_notes':''})
    (store.root/'export.json').write_text(json.dumps({'source_fingerprint':store.fingerprint(),'files':files},indent=2)+'\n')
    print(json.dumps({'created':[str(p) for p in (paper,deck,proxy)],'inspection_required':True},indent=2))


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('run')
    render(Path(parser.parse_args().run).resolve())
